version: 2
jobs:
  build:
    
    working_directory: ~/dropwizard-demos-quickies

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: dropwizard-demos-quickies-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: dropwizard-demos-quickies-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_artifacts:
          path: target/dropwizard-demos-quickies-1.0.0-SNAPSHOT.jar
