# Only for dev
data.quickie:
  image: mongo:3.3
  command: --break-mongo
db.quickie:
  image: mongo:3.3
  volumes_from:
    - data.quickie
  ports:
    - "27017:27017"
  command: --smallfiles --rest

